// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpDccidLYm3DxGw-FInkSYRCOa16eyOVI',
    appId: '1:207892664422:web:fc42f86e1186af37b05da7',
    messagingSenderId: '207892664422',
    projectId: 'online-shop-83fe0',
    authDomain: 'online-shop-83fe0.firebaseapp.com',
    storageBucket: 'online-shop-83fe0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNZA69qkcAe7s2fjRaxRt-wBkryC6hYKc',
    appId: '1:207892664422:android:6acf9c06c2be8f6fb05da7',
    messagingSenderId: '207892664422',
    projectId: 'online-shop-83fe0',
    storageBucket: 'online-shop-83fe0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDetgvJD0YoLKgUZ_YkacFHcTix2Beg7Jg',
    appId: '1:207892664422:ios:1a10d32d755ae512b05da7',
    messagingSenderId: '207892664422',
    projectId: 'online-shop-83fe0',
    storageBucket: 'online-shop-83fe0.appspot.com',
    iosBundleId: 'com.example.onlineShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDetgvJD0YoLKgUZ_YkacFHcTix2Beg7Jg',
    appId: '1:207892664422:ios:98434aa40d836a20b05da7',
    messagingSenderId: '207892664422',
    projectId: 'online-shop-83fe0',
    storageBucket: 'online-shop-83fe0.appspot.com',
    iosBundleId: 'com.example.onlineShop.RunnerTests',
  );
}
